<a href="https://colab.research.google.com/github/PericlesBritto/Google-colab_python/blob/main/curso_de_python_para_iniciantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Olá Mundo

Nosso primeiro comando em Python

In [ ]:
print("Olá Mundo")

Olá Mundo


### String

Concactenação com operador +

In [ ]:
print("Curso" + " de Python")


Curso de Python


Substituindo valores com format()

In [ ]:
print("Aula {} do Curso de {}".format(1, "Python"))

Aula 1 do Curso de Python


Transformando para minúsculas com o comando lower()

In [ ]:
print("Curso de Python para Iniciantes".lower())

curso de python para iniciantes


In [ ]:
print("Curso de Python para Iniciantes".upper())

CURSO DE PYTHON PARA INICIANTES


Removendo espaços em branco no começo e e no fim do texto com o comando strip()

In [ ]:
print("    Curso de Python para Iniciantes   ".strip())

Curso de Python para Iniciantes


O comando type exibe o tipo da variável

In [ ]:
type("Curso de Python para Iniciantes")

str

Lidando com números e Operadores Matemáticos

> Soma

In [ ]:
2 + 2

4

> Subtração

In [ ]:
4-2

2

> Multiplicação

In [ ]:
2 * 2

4

> Divisão

In [ ]:
2/5

0.4

>> Divisão inteira

In [ ]:
7 // 2

3

>> Resto da divisão

In [ ]:
7%3

1

In [ ]:
type(5/2)

float

> Exponenciação

In [ ]:
7 ** 2

49

In [ ]:
type(7 ** 2)

int

> Expressão

In [ ]:
3 * 2 + 4 / 5 ** 2

6.16

In [ ]:
(3 * 2) + (4 / 5) ** 2

6.640000000000001

In [ ]:
((3 * 2) + (4 / 5)) ** 2

46.239999999999995

# Curso de Python para iniciante - Aula 02

###Variáveis númerica

In [8]:
soma = 0
soma

0

>> Incrementando e Decrementando

In [37]:
soma = soma + 1
soma

0

In [44]:
soma += 1
soma

1

In [45]:
soma -= 1
soma

0

### Listas

> Criando e selecionando elementos de uma lista

In [48]:
frutas = ['maça', 'banana', 'laranja']
frutas

['maça', 'banana', 'laranja']

In [49]:
print(frutas)

['maça', 'banana', 'laranja']


In [50]:
print(frutas[0])

maça


In [51]:
print(frutas[1])

banana


In [52]:
print(frutas[2])

laranja


In [58]:
t1 = (frutas[2])

In [59]:
t1
print(t1)

laranja


In [61]:
numeros = [1, 2, 3, 4, 5]
numeros

[1, 2, 3, 4, 5]

In [70]:
mista = ['a', 'b', 'c', [1, 2, 3], ['maça', 'banana', 'laranja']]
mista

['a', 'b', 'c', [1, 2, 3], ['maça', 'banana', 'laranja']]

In [73]:
mista[3]

[1, 2, 3]

In [76]:
mista[4][0]

'maça'

In [82]:
mista[4][:1]

['maça']

In [92]:
mista[2:]

['c', [1, 2, 3], ['maça', 'banana', 'laranja']]

In [98]:
mista[3][3-1]

3

In [108]:
mista.append('goiaba')
mista

['a', 'b', 'c', [1, 2, 3], ['maça', 'banana', 'laranja'], 'goiaba']

In [107]:
mista

['a', 'b', 'c', [1, 2, 3], ['maça', 'banana', 'laranja']]

In [110]:
lista = mista = ['a', 'b', 'c']
lista

['a', 'b', 'c']

In [112]:
fruta = ['banana', 'laranja', 'maçã']
fruta

['banana', 'laranja', 'maçã']

In [113]:
numero = [1, 2, 3, 4, 5]
numero

[1, 2, 3, 4, 5]

In [114]:
lista.append(fruta)

In [115]:
lista.append(numero)

In [116]:
print(lista)

['a', 'b', 'c', ['banana', 'laranja', 'maçã'], [1, 2, 3, 4, 5]]


In [117]:
fruta.append('goiaba')

In [118]:
print(lista)

['a', 'b', 'c', ['banana', 'laranja', 'maçã', 'goiaba'], [1, 2, 3, 4, 5]]


In [126]:
print(lista[4][:3])

[1, 2, 3]


> Apagar um elemento de uma lista

In [129]:
print(fruta)

['banana', 'laranja', 'maçã', 'goiaba']


In [134]:
fruta.pop(3)

'goiaba'

In [135]:
fruta

['banana', 'laranja', 'maçã']

> Duas formas de duplicando um lista ou parte dela

In [143]:
frutas = fruta
frutas = fruta[0:]


In [144]:
frutas

['banana', 'laranja', 'maçã']

Alterando os valores de uma lista

In [145]:
frutas[0:] = 'pera', 'morango', 'uva'

In [146]:
print(frutas)

['pera', 'morango', 'uva']


In [148]:
lista.append(frutas)

In [149]:
print(lista)

['a', 'b', 'c', [1, 2, 3, 4, 5], ['pera', 'morango', 'uva']]


> Tuplas

In [155]:
marcas = 'gm', 'ford', 'fiat', 'vw'
marcas

('gm', 'ford', 'fiat', 'vw')

In [156]:
marcas[3]

'vw'

>> A diferença principal entre lista e Tuplas, é que nas Tuplas os valores não podem ser alterados

In [157]:
marcas[1] = 'ferrari'

TypeError: ignored

# Dicionário

In [158]:
notas = {'português':8, 'inglês':7.4, 'matemática':9}
notas

{'português': 8, 'inglês': 7.4, 'matemática': 9}

In [160]:
pessoa = {'nome':'João', 'idade':25, 'profissão':'pinto'}
pessoa

{'nome': 'João', 'idade': 25, 'profissão': 'pinto'}

In [161]:
times = {1:'flamengo', 2:'São Paulo', 3:'Grêmio' }
times

{1: 'flamengo', 2: 'São Paulo', 3: 'Grêmio'}

In [162]:
notas['matemática']

9

In [163]:
notas['português']

8

In [165]:
pessoa['nome']

'João'

In [166]:
times[3]

'Grêmio'

In [171]:
times[1]

'flamengo'

> Alterando elementos

In [172]:
notas['matemática'] = 10
notas

{'português': 8, 'inglês': 7.4, 'matemática': 10}

In [173]:
times[2] = 'Palmeiras'

In [174]:
times

{1: 'flamengo', 2: 'Palmeiras', 3: 'Grêmio'}

>> Alterando Elementos

In [176]:
notas['geografia'] = 7.1
notas

{'português': 8, 'inglês': 7.4, 'matemática': 10, 'geografia': 7.1}

In [177]:
times[85] = 'Vasco'

In [178]:
times

{1: 'flamengo', 2: 'Palmeiras', 3: 'Grêmio', 85: 'Vasco'}

# IF / ELSE

In [180]:
x = 1
y = 5

>> Operadores Lógicos

In [181]:
x == 1

True

In [182]:
x == 2

False

In [183]:
x < 0

False

In [185]:
x >= 0

True

In [186]:
x != 0

True

In [187]:
(x > 0) and (y < 2)

False

In [188]:
(x > 0) or (y < 2)

True

>> Identação Obrigatória

In [211]:
x = 0
if (x > 0):
    print("x é maior que zero")
else:
    print('x é menor ou igual a 0')

x é menor ou igual a 0


In [214]:
x = -5
if (x > 0):
    print("x é maior que zero")
elif(x == 0):
    print("x é zero")
else:
    print('x é menor 0')

x é menor 0


>> Uso do FOR (comando de repetição)

In [216]:
contador = [0,1,2,3,4,5,6,7,8,9]
contador

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [217]:
for valor in contador:
    print(valor)

0
1
2
3
4
5
6
7
8
9


In [221]:
range?

In [223]:
for valor in range(10):
    print(valor)

0
1
2
3
4
5
6
7
8
9


In [224]:
for i in range(4,18,2):
    print(i)

4
6
8
10
12
14
16


In [225]:
cidades = ['São Paulo', 'Brasília', 'Curitiba']
cidades

['São Paulo', 'Brasília', 'Curitiba']

In [228]:
for cidade in cidades:
    print("Já morei em " + cidade)

Já morei em São Paulo
Já morei em Brasília
Já morei em Curitiba


In [229]:
minha_lista = [1,2,3,'cachorro', 'gato', 'papagáio']
minha_lista

[1, 2, 3, 'cachorro', 'gato', 'papagáio']

In [231]:
for cada_item in minha_lista:
    print(cada_item)

1
2
3
cachorro
gato
papagáio


>> Uso do WHILE (comando de repetição)

In [233]:
x = 0
while x  < 5:
  print(x)
  x += 1

0
1
2
3
4


List Comprehensions

In [236]:
quadrados = []
for numero in range(10):
  quadrados.append(numero**2)
quadrados

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

>> Uma maneira mais concisa de criar listas

In [237]:
quad = [x**2 for x in range(10)]
quad

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# FUNÇÕES

>> Funções que não retorna valor

In [239]:
def exibir_mensagem(parametro):
  print("mensagem >> " + parametro)

In [240]:
exibir_mensagem('Olá !!!')

mensagem >> Olá !!!


In [241]:
exibir_mensagem('Olá Mundo !!')

mensagem >> Olá Mundo !!


In [246]:
 def exibir_dados(nome, idade):
    print("Meu nome é {}".format(nome))
    print("Tenho {} anos.".format(idade))

In [247]:
exibir_dados('Maria', 70)

Meu nome é Maria
Tenho 70 anos.


In [248]:
exibir_dados("Paulor", 12)

Meu nome é Paulor
Tenho 12 anos.


>> Funções que retorna valor

In [250]:
def elevar_ao_quadrado(numero):
  return(numero ** 2)

In [252]:
elevar_ao_quadrado(4)

16

In [253]:
elevar_ao_quadrado(252)

63504

# Bibliotecas

>> Já instalada no ambiente do Google Colab

In [254]:
import numpy

In [255]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

>> Utilizando um apelido para a função

In [256]:
import numpy as np

In [261]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [258]:
from numpy import ones

In [260]:
ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

>> Instalando Bibliotecas Externas

In [263]:
!pip install yfinance

In [265]:
import yfinance as yf

In [267]:
yf.download('^BVSP')

[*********************100%***********************]  1 of 1 completed


Open           High            Low          Close  \
Date                                                                     
1993-04-27      24.799999      25.400000      24.500000      24.500000   
1993-04-28      24.500000      24.600000      23.700001      24.299999   
1993-04-29      24.299999      24.799999      23.700001      23.700001   
1993-04-30      23.700001      24.200001      23.700001      24.100000   
1993-05-03      24.100000      24.400000      23.799999      24.100000   
...                   ...            ...            ...            ...   
2023-07-21  118090.000000  120373.000000  118086.000000  120217.000000   
2023-07-24  120220.000000  121772.000000  120099.000000  121342.000000   
2023-07-25  121344.000000  123010.000000  121344.000000  122008.000000   
2023-07-26  122003.000000  122747.000000  121370.000000  122560.000000   
2023-07-27  122560.000000  122599.000000  119825.000000  119990.000000   

                Adj Close    Volume  
Date                                 
1993-04-27      24.500000         0  
1993-04-28      24.299999         0  
1993-04-29      23.700001         0  
1993-04-30      24.100000         0  
1993-05-03      24.100000         0  
...                   ...       ...  
2023-07-21  120217.000000  11181500  
2023-07-24  121342.000000  10494800  
2023-07-25  122008.000000  11427100  
2023-07-26  122560.000000   9988800  
2023-07-27  119990.000000  10678700  

[7488 rows x 6 columns]